name: Java Continuous Integration with Maven

on:
  push:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'
          cache: 'maven'
          cache-dependency-path: 'sub-project/pom.xml'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run tests with JUnit
        run: mvn test
